// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ChatChatStreamData, ChatChatStreamResponse, ChatGradeExerciseData, ChatGradeExerciseResponse, DictionaryListWordsData, DictionaryListWordsResponse, DictionaryGetWordDetailData, DictionaryGetWordDetailResponse, DictionaryListGrammarResponse, DictionaryGetGrammarSectionDetailData, DictionaryGetGrammarSectionDetailResponse, LessonsListUnitsResponse, LessonsGetLessonExercisesData, LessonsGetLessonExercisesResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserData, PrivateCreateUserResponse, ProgressGetMyProgressResponse, ProgressUpdateMyProgressData, ProgressUpdateMyProgressResponse, ProgressSyncProgressData, ProgressSyncProgressResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class ChatService {
    /**
     * Chat Stream
     * Stream a chat response from the LLM.
     *
     * Anonymous users: rate-limited to CHAT_FREE_DAILY_LIMIT/day, max_tokens capped.
     * Authenticated users: exempt from rate limit, higher max_tokens.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static chatStream(data: ChatChatStreamData): CancelablePromise<ChatChatStreamResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/chat/stream',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Grade Exercise
     * Grade a free-form toki pona exercise using the LLM.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ExerciseGradeResponse Successful Response
     * @throws ApiError
     */
    public static gradeExercise(data: ChatGradeExerciseData): CancelablePromise<ChatGradeExerciseResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/chat/grade',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class DictionaryService {
    /**
     * List Words
     * Search and filter dictionary words.
     *
     * Query params:
     * q: Search text (matches word name and definitions).
     * pos: Part of speech filter (e.g. "noun", "verb", "particle").
     * word_set: Word set filter — "pu" for core words, "ku" for ku words.
     * @param data The data for the request.
     * @param data.q
     * @param data.pos
     * @param data.wordSet
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static listWords(data: DictionaryListWordsData = {}): CancelablePromise<DictionaryListWordsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/dictionary/words',
            query: {
                q: data.q,
                pos: data.pos,
                word_set: data.wordSet
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Word Detail
     * Get details for a single word.
     * @param data The data for the request.
     * @param data.word
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static getWordDetail(data: DictionaryGetWordDetailData): CancelablePromise<DictionaryGetWordDetailResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/dictionary/words/{word}',
            path: {
                word: data.word
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Grammar
     * Get all grammar content: sections, comparisons, and quiz.
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static listGrammar(): CancelablePromise<DictionaryListGrammarResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/dictionary/grammar'
        });
    }
    
    /**
     * Get Grammar Section Detail
     * Get a single grammar section by id.
     * @param data The data for the request.
     * @param data.sectionId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static getGrammarSectionDetail(data: DictionaryGetGrammarSectionDetailData): CancelablePromise<DictionaryGetGrammarSectionDetailResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/dictionary/grammar/{section_id}',
            path: {
                section_id: data.sectionId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LessonsService {
    /**
     * List Units
     * Return the full skill tree — all 10 units with metadata.
     * @returns UnitSummary Successful Response
     * @throws ApiError
     */
    public static listUnits(): CancelablePromise<LessonsListUnitsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/lessons/units'
        });
    }
    
    /**
     * Get Lesson Exercises
     * Return exercises for a specific lesson within a unit.
     * @param data The data for the request.
     * @param data.unitId
     * @param data.lessonId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static getLessonExercises(data: LessonsGetLessonExercisesData): CancelablePromise<LessonsGetLessonExercisesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/lessons/units/{unit_id}/lessons/{lesson_id}',
            path: {
                unit_id: data.unitId,
                lesson_id: data.lessonId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ProgressService {
    /**
     * Get My Progress
     * Return the authenticated user's progress. Creates a default record if none exists.
     * @returns ProgressPublic Successful Response
     * @throws ApiError
     */
    public static getMyProgress(): CancelablePromise<ProgressGetMyProgressResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/progress/me'
        });
    }
    
    /**
     * Update My Progress
     * Partial update of the authenticated user's progress.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ProgressPublic Successful Response
     * @throws ApiError
     */
    public static updateMyProgress(data: ProgressUpdateMyProgressData): CancelablePromise<ProgressUpdateMyProgressResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/progress/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Sync Progress
     * Merge localStorage progress into the server record.
     *
     * Uses max/union strategy so the operation is idempotent.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ProgressPublic Successful Response
     * @throws ApiError
     */
    public static syncProgress(data: ProgressSyncProgressData): CancelablePromise<ProgressSyncProgressResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/progress/sync',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}