// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ChatMessage = {
    role: string;
    content: string;
};

export type ChatRequest = {
    messages: Array<ChatMessage>;
    mode?: string;
    known_words?: Array<(string)>;
    current_unit?: number;
    recent_errors?: Array<{
        [key: string]: unknown;
    }>;
};

export type ExerciseGradeRequest = {
    exercise_type: string;
    prompt: string;
    user_answer: string;
    known_words?: Array<(string)>;
};

export type ExerciseGradeResponse = {
    correct: boolean;
    score: number;
    feedback: string;
    suggested_answer?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Response schema for progress endpoints.
 */
export type ProgressPublic = {
    completed_units?: Array<(number)>;
    completed_lessons?: Array<(string)>;
    current_unit?: number;
    srs_data?: {
        [key: string]: unknown;
    };
    total_correct?: number;
    total_answered?: number;
    streak_days?: number;
    last_activity?: (string | null);
    known_words?: Array<(string)>;
    recent_errors?: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * Payload for POST /progress/sync — localStorage data to merge.
 */
export type ProgressSync = {
    completed_units?: Array<(number)>;
    completed_lessons?: Array<(string)>;
    current_unit?: number;
    srs_data?: {
        [key: string]: unknown;
    };
    total_correct?: number;
    total_answered?: number;
    streak_days?: number;
    last_activity?: (string | null);
    known_words?: Array<(string)>;
    recent_errors?: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * Partial update payload for PUT /progress/me.
 */
export type ProgressUpdate = {
    completed_units?: (Array<(number)> | null);
    completed_lessons?: (Array<(string)> | null);
    current_unit?: (number | null);
    srs_data?: ({
    [key: string]: unknown;
} | null);
    total_correct?: (number | null);
    total_answered?: (number | null);
    streak_days?: (number | null);
    last_activity?: (string | null);
    known_words?: (Array<(string)> | null);
    recent_errors?: (Array<{
    [key: string]: unknown;
}> | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * Unit metadata returned by the units list endpoint.
 */
export type UnitSummary = {
    id: number;
    name: string;
    topic: string;
    words: Array<(string)>;
    exercise_types: Array<(string)>;
    requires: Array<(number)>;
    lesson_count: number;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
    invite_token?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ChatChatStreamData = {
    requestBody: ChatRequest;
};

export type ChatChatStreamResponse = (unknown);

export type ChatGradeExerciseData = {
    requestBody: ExerciseGradeRequest;
};

export type ChatGradeExerciseResponse = (ExerciseGradeResponse);

export type ConfigGetPublicConfigResponse = ({
    [key: string]: unknown;
});

export type DictionaryListWordsData = {
    pos?: (string | null);
    q?: (string | null);
    wordSet?: (string | null);
};

export type DictionaryListWordsResponse = (Array<{
    [key: string]: unknown;
}>);

export type DictionaryGetWordDetailData = {
    word: string;
};

export type DictionaryGetWordDetailResponse = ({
    [key: string]: unknown;
});

export type DictionaryListGrammarResponse = ({
    [key: string]: unknown;
});

export type DictionaryGetGrammarSectionDetailData = {
    sectionId: string;
};

export type DictionaryGetGrammarSectionDetailResponse = ({
    [key: string]: unknown;
});

export type LessonsListUnitsResponse = (Array<UnitSummary>);

export type LessonsGetLessonExercisesData = {
    lessonId: number;
    unitId: number;
};

export type LessonsGetLessonExercisesResponse = ({
    [key: string]: unknown;
});

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProgressGetMyProgressResponse = (ProgressPublic);

export type ProgressUpdateMyProgressData = {
    requestBody: ProgressUpdate;
};

export type ProgressUpdateMyProgressResponse = (ProgressPublic);

export type ProgressSyncProgressData = {
    requestBody: ProgressSync;
};

export type ProgressSyncProgressResponse = (ProgressPublic);

export type TelegramTelegramWebhookResponse = ({
    [key: string]: unknown;
});

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersValidateTokenData = {
    token: string;
};

export type UsersValidateTokenResponse = ({
    [key: string]: (boolean);
});

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);