"""add unique constraint to user_progress user_id

Revision ID: 22923932d3d9
Revises: 59b6c3802e28
Create Date: 2026-04-05 16:17:13.771872

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '22923932d3d9'
down_revision = '59b6c3802e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userprogress_user_id'), table_name='userprogress')
    op.create_index(op.f('ix_userprogress_user_id'), 'userprogress', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userprogress_user_id'), table_name='userprogress')
    op.create_index(op.f('ix_userprogress_user_id'), 'userprogress', ['user_id'], unique=False)
    # ### end Alembic commands ###
