"""add user_progress table

Revision ID: 59b6c3802e28
Revises: a129d15d8fda
Create Date: 2026-04-05 15:39:17.152193

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '59b6c3802e28'
down_revision = 'a129d15d8fda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userprogress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('completed_units', sa.JSON(), nullable=True),
    sa.Column('completed_lessons', sa.JSON(), nullable=True),
    sa.Column('current_unit', sa.Integer(), nullable=False),
    sa.Column('srs_data', sa.JSON(), nullable=True),
    sa.Column('total_correct', sa.Integer(), nullable=False),
    sa.Column('total_answered', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('known_words', sa.JSON(), nullable=True),
    sa.Column('recent_errors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userprogress_user_id'), 'userprogress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userprogress_user_id'), table_name='userprogress')
    op.drop_table('userprogress')
    # ### end Alembic commands ###
