"""add access_request and invite_token tables

Revision ID: b10ca8e00c85
Revises: ffcdfc63477d
Create Date: 2026-04-06 07:19:52.201308

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b10ca8e00c85'
down_revision = 'ffcdfc63477d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.Integer(), nullable=False),
    sa.Column('telegram_username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('telegram_first_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('telegram_last_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_request_telegram_user_id'), 'access_request', ['telegram_user_id'], unique=False)
    op.create_table('invite_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('access_request_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['access_request_id'], ['access_request.id'], ),
    sa.ForeignKeyConstraint(['used_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_token_token'), 'invite_token', ['token'], unique=True)
    op.alter_column('user_progress', 'last_activity',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_progress', 'last_activity',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_invite_token_token'), table_name='invite_token')
    op.drop_table('invite_token')
    op.drop_index(op.f('ix_access_request_telegram_user_id'), table_name='access_request')
    op.drop_table('access_request')
    # ### end Alembic commands ###
