/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutGrammarIndexRouteImport } from './routes/_layout/grammar/index'
import { Route as LayoutDictionaryIndexRouteImport } from './routes/_layout/dictionary/index'
import { Route as LayoutGrammarParticlesRouteImport } from './routes/_layout/grammar/particles'
import { Route as LayoutGrammarModifiersRouteImport } from './routes/_layout/grammar/modifiers'
import { Route as LayoutDictionaryWordRouteImport } from './routes/_layout/dictionary/$word'
import { Route as LayoutLearnUnitLessonRouteImport } from './routes/_layout/learn/$unit.$lesson'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGrammarIndexRoute = LayoutGrammarIndexRouteImport.update({
  id: '/grammar/',
  path: '/grammar/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDictionaryIndexRoute = LayoutDictionaryIndexRouteImport.update({
  id: '/dictionary/',
  path: '/dictionary/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGrammarParticlesRoute = LayoutGrammarParticlesRouteImport.update({
  id: '/grammar/particles',
  path: '/grammar/particles',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGrammarModifiersRoute = LayoutGrammarModifiersRouteImport.update({
  id: '/grammar/modifiers',
  path: '/grammar/modifiers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDictionaryWordRoute = LayoutDictionaryWordRouteImport.update({
  id: '/dictionary/$word',
  path: '/dictionary/$word',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLearnUnitLessonRoute = LayoutLearnUnitLessonRouteImport.update({
  id: '/learn/$unit/$lesson',
  path: '/learn/$unit/$lesson',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/settings': typeof LayoutSettingsRoute
  '/dictionary/$word': typeof LayoutDictionaryWordRoute
  '/grammar/modifiers': typeof LayoutGrammarModifiersRoute
  '/grammar/particles': typeof LayoutGrammarParticlesRoute
  '/dictionary/': typeof LayoutDictionaryIndexRoute
  '/grammar/': typeof LayoutGrammarIndexRoute
  '/learn/$unit/$lesson': typeof LayoutLearnUnitLessonRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/dictionary/$word': typeof LayoutDictionaryWordRoute
  '/grammar/modifiers': typeof LayoutGrammarModifiersRoute
  '/grammar/particles': typeof LayoutGrammarParticlesRoute
  '/dictionary': typeof LayoutDictionaryIndexRoute
  '/grammar': typeof LayoutGrammarIndexRoute
  '/learn/$unit/$lesson': typeof LayoutLearnUnitLessonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/dictionary/$word': typeof LayoutDictionaryWordRoute
  '/_layout/grammar/modifiers': typeof LayoutGrammarModifiersRoute
  '/_layout/grammar/particles': typeof LayoutGrammarParticlesRoute
  '/_layout/dictionary/': typeof LayoutDictionaryIndexRoute
  '/_layout/grammar/': typeof LayoutGrammarIndexRoute
  '/_layout/learn/$unit/$lesson': typeof LayoutLearnUnitLessonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/settings'
    | '/dictionary/$word'
    | '/grammar/modifiers'
    | '/grammar/particles'
    | '/dictionary/'
    | '/grammar/'
    | '/learn/$unit/$lesson'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/settings'
    | '/'
    | '/dictionary/$word'
    | '/grammar/modifiers'
    | '/grammar/particles'
    | '/dictionary'
    | '/grammar'
    | '/learn/$unit/$lesson'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/dictionary/$word'
    | '/_layout/grammar/modifiers'
    | '/_layout/grammar/particles'
    | '/_layout/dictionary/'
    | '/_layout/grammar/'
    | '/_layout/learn/$unit/$lesson'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/grammar/': {
      id: '/_layout/grammar/'
      path: '/grammar'
      fullPath: '/grammar/'
      preLoaderRoute: typeof LayoutGrammarIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dictionary/': {
      id: '/_layout/dictionary/'
      path: '/dictionary'
      fullPath: '/dictionary/'
      preLoaderRoute: typeof LayoutDictionaryIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/grammar/particles': {
      id: '/_layout/grammar/particles'
      path: '/grammar/particles'
      fullPath: '/grammar/particles'
      preLoaderRoute: typeof LayoutGrammarParticlesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/grammar/modifiers': {
      id: '/_layout/grammar/modifiers'
      path: '/grammar/modifiers'
      fullPath: '/grammar/modifiers'
      preLoaderRoute: typeof LayoutGrammarModifiersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dictionary/$word': {
      id: '/_layout/dictionary/$word'
      path: '/dictionary/$word'
      fullPath: '/dictionary/$word'
      preLoaderRoute: typeof LayoutDictionaryWordRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/learn/$unit/$lesson': {
      id: '/_layout/learn/$unit/$lesson'
      path: '/learn/$unit/$lesson'
      fullPath: '/learn/$unit/$lesson'
      preLoaderRoute: typeof LayoutLearnUnitLessonRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutDictionaryWordRoute: typeof LayoutDictionaryWordRoute
  LayoutGrammarModifiersRoute: typeof LayoutGrammarModifiersRoute
  LayoutGrammarParticlesRoute: typeof LayoutGrammarParticlesRoute
  LayoutDictionaryIndexRoute: typeof LayoutDictionaryIndexRoute
  LayoutGrammarIndexRoute: typeof LayoutGrammarIndexRoute
  LayoutLearnUnitLessonRoute: typeof LayoutLearnUnitLessonRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutDictionaryWordRoute: LayoutDictionaryWordRoute,
  LayoutGrammarModifiersRoute: LayoutGrammarModifiersRoute,
  LayoutGrammarParticlesRoute: LayoutGrammarParticlesRoute,
  LayoutDictionaryIndexRoute: LayoutDictionaryIndexRoute,
  LayoutGrammarIndexRoute: LayoutGrammarIndexRoute,
  LayoutLearnUnitLessonRoute: LayoutLearnUnitLessonRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
